#!/bin/bash

IMAGE=$1
shift
X=$1
shift
Y=$1

convert $IMAGE -crop 420x150+$X+$Y "${IMAGE%.*}-edit.jpg"


#def getprediction(arg0):
#image_data = tf.gfile.FastGFile(arg0 + ".jpg", 'rb').read()
#with tf.Session() as session:
#  softmax_tensor = session.graph.get_tensor_by_name('final_result:0')

#  predictions = session.run(softmax_tensor, \
# {'DecodeJpeg/contents:0':image_data})
#top_k=predictions[0].argsort()[-len(predictions[0]):][::-1]
#scores = "";
#for node_id in top_k:
#human_string = label_lines[node_id]
#score = predictions[0][node_id]
#return (human_string, score)
#return ()
